services:
  nginx:
    image: nginx:1.25-alpine
    container_name: ecommerce_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - admin-service
      - api-gateway
    networks:
      - ecommerce_net

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    container_name: ecommerce_admin_service
    ports:
      - "5173:5173"
    depends_on:
      - db
      - redis
    networks:
      - ecommerce_net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: ecommerce_api_gateway
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - db
      - redis
    networks:
      - ecommerce_net

  db:
    image: postgres:16-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce_net

networks:
  ecommerce_net:

volumes:
  db_data: