services:
  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./admin-service:/var/www/admin-service
      - admin-build:/var/www/admin-service/public/build

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    volumes:
      - ./admin-service:/var/www/admin-service:ro
      - admin-build:/var/www/admin-service/public/build:ro

volumes:
  admin-build: