name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push admin-service
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ecommerce-admin:latest ./admin-service
          docker push ghcr.io/${{ github.repository_owner }}/ecommerce-admin:latest

      - name: Build & Push api-gateway
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ecommerce-api-gateway:latest ./api-gateway
          docker push ghcr.io/${{ github.repository_owner }}/ecommerce-api-gateway:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/your/project
            docker compose pull
            docker compose up -d
            docker image prune -f